name: Push quickstart scripts to S3
on: 
    push: 
      branches:
        - eob-devel
      tags:
        - eob
jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set location to push
      id: s3-path
      run: |
        if [[ $GITHUB_REF_NAME == "eob" && $GITHUB_REF_TYPE == "tag" ]]; then
        echo "S3_LOCATION=vars.S3_BUCKET" >> $GITHUB_ENV
        fi

        if [[ $GITHUB_REF_NAME == "eob-devel" && $GITHUB_REF_TYPE == "branch" ]]; then
          echo "S3_LOCATION=vars.S3_BUCKET/dev" >> $GITHUB_ENV
        fi
    
    - name: Print the path
      run: |
        echo "S3 Bucket is ${{ vars.S3_BUCKET }}"
        echo "S3 Path is ${{ env.S3_LOCATION }}"
        

    # - name: Authenticate with AWS

    # - name: Push quickstart scripts to S3
