name: Push quickstart scripts to S3
on: 
    push: 
      branches:
        - eob-devel
      tags:
        - eob
jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set location to push
      id: s3-path
      run: |
        if [[ $GITHUB_REF_NAME == "eob" && $GITHUB_REF_TYPE == "tag" ]]; then
          echo "TRIGGER=eob-tag" >> $GITHUB_ENV
          echo "S3_LOCATION=s3://${{ vars.S3_BUCKET }}" >> $GITHUB_ENV
        fi

        if [[ $GITHUB_REF_NAME == "eob-devel" && $GITHUB_REF_TYPE == "branch" ]]; then
          echo "TRIGGER=eob-devel-branch" >> $GITHUB_ENV
          echo "S3_LOCATION=s3://${{ vars.S3_BUCKET }}/dev" >> $GITHUB_ENV
        fi
  
    - name: Print the path
      run: |
        echo "Trigger is ${{ env.TRIGGER }}"
        echo "S3 Bucket is ${{ vars.S3_BUCKET }}"
        echo "S3 Path is ${{ env.S3_LOCATION }}"
        

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Push quickstart scripts to S3
      run:
        for csp in aws azure gcp
        do
          echo "aws s3 cp ${csp}/quickstart.sh ${{ env.S3_LOCATION }}/${csp}/"
        done
